#
# Copyright (c) 2022 Amazon.com, Inc. or its affiliates.  All rights reserved.
#
# PROPRIETARY/CONFIDENTIAL.  USE IS SUBJECT TO LICENSE TERMS.
#
schema-version = 1

[package]
title = "Basic UI React Native Application"
version = "0.2.2"
id = "com.truex.keplerrefapp"

[components]
[[components.interactive]]
id = "com.truex.keplerrefapp.main"
categories = ["com.amazon.category.main"]
runtime-module = "/com.amazon.kepler.keplerscript.runtime.loader_2@IKeplerScript_2_0"
launch-type = "singleton"

[wants]
[[wants.service]]
id = "com.amazon.inputmethod.service"

# For rendering web content
[[wants.service]]
id = "com.amazon.webview.renderer_service"

# For video playback
[[wants.service]]
id = "com.amazon.media.server"

[[wants.service]]
id = "com.amazon.mediabuffer.service"

[[wants.service]]
id = "com.amazon.mediatransform.service"

[[wants.service]]
id = "com.amazon.mediametrics.service"

#Required for remote button events.
[[wants.service]]
id = "com.amazon.inputd.service"

#Required to connect to MediaControls
[[wants.service]]
id = "com.amazon.media.playersession.service"

#Required for GIPC SR
[[wants.service]]
id = "com.amazon.gipc.uuid.*"

#Required for using the audio stream
[[wants.service]]
id = "com.amazon.audio.stream"

#Required for using Volume and Other controls
[[wants.service]]
id = "com.amazon.audio.control"

#Required for using Volume and Other controls
[[wants.service]]
id = "com.amazon.audio.system"

# To enable accessibility support for your app,
# it's highly recommended you add UCC service with SR
[[wants.service]]
id = "com.amazon.kepler.ucc.publisher"

#Required for GIPC SR
[[offers.service]]
id = "com.amazon.gipc.uuid.*"

[[needs.module]]
id = "/com.amazon.kepler.webview@IWebView"
